/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 13 20:18:01 GMT 2021
 */

package org.apache.xml.security.stax.impl.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.security.MessageDigest;
import org.apache.xml.security.stax.impl.util.DigestOutputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DigestOutputStream_ESTest extends DigestOutputStream_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DigestOutputStream digestOutputStream0 = new DigestOutputStream((MessageDigest) null);
      // Undeclared exception!
      try { 
        digestOutputStream0.write((byte[]) null, 1027, (-1242));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xml.security.stax.impl.util.DigestOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DigestOutputStream digestOutputStream0 = new DigestOutputStream((MessageDigest) null);
      // Undeclared exception!
      try { 
        digestOutputStream0.write((-2325));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xml.security.stax.impl.util.DigestOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DigestOutputStream digestOutputStream0 = new DigestOutputStream((MessageDigest) null);
      // Undeclared exception!
      try { 
        digestOutputStream0.getDigestValue();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xml.security.stax.impl.util.DigestOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DigestOutputStream digestOutputStream0 = new DigestOutputStream((MessageDigest) null);
      byte[] byteArray0 = new byte[2];
      // Undeclared exception!
      try { 
        digestOutputStream0.write(byteArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.xml.security.stax.impl.util.DigestOutputStream", e);
      }
  }
}
