/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 13 17:27:40 GMT 2021
 */

package org.apache.xml.security.configuration;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.xml.security.configuration.InOutAttrType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InOutAttrType_ESTest extends InOutAttrType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InOutAttrType[] inOutAttrTypeArray0 = InOutAttrType.values();
      assertEquals(2, inOutAttrTypeArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      InOutAttrType inOutAttrType0 = InOutAttrType.valueOf("OUT");
      assertEquals(InOutAttrType.OUT, inOutAttrType0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      InOutAttrType inOutAttrType0 = InOutAttrType.fromValue("OUT");
      assertEquals(InOutAttrType.OUT, inOutAttrType0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      InOutAttrType inOutAttrType0 = InOutAttrType.OUT;
      String string0 = inOutAttrType0.value();
      assertEquals("OUT", string0);
  }
}
