/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 13 17:19:55 GMT 2021
 */

package org.apache.xml.security.configuration;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.xml.security.configuration.ResolverType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ResolverType_ESTest extends ResolverType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ResolverType resolverType0 = new ResolverType();
      resolverType0.setValue("-6w]D.B@@&Duc'd.i[");
      String string0 = resolverType0.getValue();
      assertEquals("-6w]D.B@@&Duc'd.i[", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ResolverType resolverType0 = new ResolverType();
      resolverType0.setJAVACLASS("");
      String string0 = resolverType0.getJAVACLASS();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ResolverType resolverType0 = new ResolverType();
      resolverType0.setDESCRIPTION("");
      String string0 = resolverType0.getDESCRIPTION();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ResolverType resolverType0 = new ResolverType();
      String string0 = resolverType0.getValue();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ResolverType resolverType0 = new ResolverType();
      String string0 = resolverType0.getDESCRIPTION();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ResolverType resolverType0 = new ResolverType();
      resolverType0.setDESCRIPTION("EMg");
      String string0 = resolverType0.getDESCRIPTION();
      assertEquals("EMg", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ResolverType resolverType0 = new ResolverType();
      String string0 = resolverType0.getJAVACLASS();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ResolverType resolverType0 = new ResolverType();
      resolverType0.setValue("");
      String string0 = resolverType0.getValue();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ResolverType resolverType0 = new ResolverType();
      resolverType0.setJAVACLASS("EMg");
      String string0 = resolverType0.getJAVACLASS();
      assertEquals("EMg", string0);
  }
}
