/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 13 21:26:40 GMT 2021
 */

package org.apache.xml.security.keys.storage;

import org.junit.Test;
import static org.junit.Assert.*;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;
import java.util.Iterator;
import org.apache.xml.security.keys.storage.implementations.SingleCertificateResolver;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StorageResolverSpi_ESTest extends StorageResolverSpi_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SingleCertificateResolver singleCertificateResolver0 = new SingleCertificateResolver((X509Certificate) null);
      Iterator<Certificate> iterator0 = singleCertificateResolver0.getIterator();
      assertNotNull(iterator0);
  }
}
