/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun Apr 04 06:47:14 GMT 2021
 */

package com.graphhopper.routing;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class MultiplePointsNotFoundException_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.graphhopper.routing.MultiplePointsNotFoundException"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "BR"); 
    java.lang.System.setProperty("user.dir", "/home/cassioegc/tcc/graphhopper.reader-osm/core"); 
    java.lang.System.setProperty("user.home", "/home/cassioegc"); 
    java.lang.System.setProperty("user.language", "pt"); 
    java.lang.System.setProperty("user.name", "cassioegc"); 
    java.lang.System.setProperty("user.timezone", ""); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(MultiplePointsNotFoundException_ESTest_scaffolding.class.getClassLoader() ,
      "com.carrotsearch.hppc.IntIndexedContainer",
      "com.carrotsearch.hppc.IntStack",
      "com.carrotsearch.hppc.Preallocable",
      "com.graphhopper.routing.MultiplePointsNotFoundException",
      "com.carrotsearch.hppc.IntContainer",
      "com.carrotsearch.hppc.predicates.IntPredicate",
      "com.carrotsearch.hppc.IntCollection",
      "com.carrotsearch.hppc.ArraySizingStrategy",
      "com.carrotsearch.hppc.AbstractIntCollection",
      "com.carrotsearch.hppc.BoundedProportionalArraySizingStrategy",
      "com.carrotsearch.hppc.BufferAllocationException",
      "com.carrotsearch.hppc.IntArrayList",
      "com.carrotsearch.hppc.IntLookupContainer",
      "com.carrotsearch.hppc.procedures.IntProcedure"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(MultiplePointsNotFoundException_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.graphhopper.routing.MultiplePointsNotFoundException",
      "com.carrotsearch.hppc.AbstractIntCollection",
      "com.carrotsearch.hppc.IntArrayList",
      "com.carrotsearch.hppc.BoundedProportionalArraySizingStrategy",
      "com.carrotsearch.hppc.IntStack",
      "com.carrotsearch.hppc.AbstractIterator",
      "com.carrotsearch.hppc.IntArrayList$ValueIterator",
      "com.carrotsearch.hppc.cursors.IntCursor",
      "org.hsqldb.jdbc.JDBCDriver",
      "com.carrotsearch.hppc.IntByteHashMap",
      "com.carrotsearch.hppc.HashOrderMixing$1",
      "com.carrotsearch.hppc.HashOrderMixing",
      "com.carrotsearch.hppc.HashOrderMixing$4",
      "com.carrotsearch.hppc.HashOrderMixing$Strategy",
      "com.carrotsearch.hppc.Containers",
      "com.carrotsearch.hppc.Containers$1",
      "com.carrotsearch.hppc.BitMixer",
      "com.carrotsearch.hppc.RandomizedHashOrderMixer",
      "com.carrotsearch.hppc.HashContainers",
      "com.carrotsearch.hppc.IntFloatHashMap",
      "com.carrotsearch.hppc.IntFloatScatterMap",
      "com.carrotsearch.hppc.HashOrderMixing$3",
      "com.carrotsearch.hppc.BufferAllocationException",
      "com.carrotsearch.hppc.IntIntHashMap",
      "com.carrotsearch.hppc.IntIntScatterMap",
      "com.carrotsearch.hppc.IntObjectHashMap",
      "com.carrotsearch.hppc.IntObjectScatterMap",
      "com.carrotsearch.hppc.IntLongHashMap",
      "com.carrotsearch.hppc.BitUtil",
      "com.carrotsearch.hppc.IntLongHashMap$KeysContainer",
      "com.carrotsearch.hppc.IntLongHashMap$KeysIterator",
      "com.carrotsearch.hppc.IntHashSet",
      "com.carrotsearch.hppc.IntHashSet$EntryIterator",
      "com.carrotsearch.hppc.IntIntHashMap$KeysContainer",
      "com.carrotsearch.hppc.IntIntHashMap$KeysIterator",
      "com.carrotsearch.hppc.IntScatterSet",
      "com.carrotsearch.hppc.IntByteScatterMap",
      "com.carrotsearch.hppc.IntArrayDeque",
      "com.carrotsearch.hppc.IntArrayDeque$ValueIterator",
      "com.carrotsearch.hppc.IntLongScatterMap",
      "com.carrotsearch.hppc.IntShortHashMap",
      "com.carrotsearch.hppc.IntLongHashMap$EntryIterator",
      "com.carrotsearch.hppc.cursors.IntLongCursor",
      "com.carrotsearch.hppc.IntObjectHashMap$KeysContainer",
      "com.carrotsearch.hppc.IntObjectHashMap$KeysContainer$2",
      "com.carrotsearch.hppc.IntLongHashMap$KeysContainer$2"
    );
  }
}
