/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 14 20:20:48 GMT 2021
 */

package com.ibm.watson.data.client.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.ibm.watson.data.client.model.ColumnDetail;
import com.ibm.watson.data.client.model.ColumnTypeDetails;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ColumnDetail_ESTest extends ColumnDetail_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      ColumnTypeDetails columnTypeDetails0 = new ColumnTypeDetails();
      columnDetail0.setType(columnTypeDetails0);
      ColumnTypeDetails columnTypeDetails1 = columnDetail0.getType();
      assertNull(columnTypeDetails1.getScale());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      Double double0 = new Double(262.2);
      columnDetail0.setPosition(double0);
      Double double1 = columnDetail0.getPosition();
      assertEquals(262.2, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      Double double0 = new Double((-822.9373668));
      columnDetail0.setPosition(double0);
      Double double1 = columnDetail0.getPosition();
      assertEquals((-822.9373668), (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      columnDetail0.setOmrsGuid("null");
      String string0 = columnDetail0.getOmrsGuid();
      assertEquals("null", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      columnDetail0.setName("K2*/gy0FQ(o{>8d");
      String string0 = columnDetail0.getName();
      assertEquals("K2*/gy0FQ(o{>8d", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      columnDetail0.setOmrsGuid("class ColumnDetail {\n    name: null\n    omrsGuid: null\n    position: null\n    type: null\n}");
      String string0 = columnDetail0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      ColumnDetail columnDetail1 = new ColumnDetail();
      assertTrue(columnDetail1.equals((Object)columnDetail0));
      
      ColumnTypeDetails columnTypeDetails0 = new ColumnTypeDetails();
      columnDetail0.setType(columnTypeDetails0);
      boolean boolean0 = columnDetail0.equals(columnDetail1);
      assertFalse(columnDetail1.equals((Object)columnDetail0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      ColumnDetail columnDetail1 = new ColumnDetail();
      boolean boolean0 = columnDetail0.equals(columnDetail1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      ColumnDetail columnDetail1 = new ColumnDetail();
      assertTrue(columnDetail1.equals((Object)columnDetail0));
      
      columnDetail1.setOmrsGuid("class ColumnDetail {\n    name: null\n    omrsGuid: null\n    position: null\n    type: null\n}");
      boolean boolean0 = columnDetail0.equals(columnDetail1);
      assertFalse(columnDetail1.equals((Object)columnDetail0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      ColumnDetail columnDetail1 = new ColumnDetail();
      columnDetail1.setName(">!E(TU6o=>k<@");
      boolean boolean0 = columnDetail0.equals(columnDetail1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      Object object0 = new Object();
      boolean boolean0 = columnDetail0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      boolean boolean0 = columnDetail0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      boolean boolean0 = columnDetail0.equals(columnDetail0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      ColumnDetail columnDetail1 = new ColumnDetail();
      assertTrue(columnDetail1.equals((Object)columnDetail0));
      
      Double double0 = new Double(0.0);
      columnDetail0.setPosition(double0);
      boolean boolean0 = columnDetail0.equals(columnDetail1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      columnDetail0.hashCode();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      Double double0 = columnDetail0.getPosition();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      ColumnTypeDetails columnTypeDetails0 = columnDetail0.getType();
      assertNull(columnTypeDetails0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      String string0 = columnDetail0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      columnDetail0.setOmrsGuid("");
      String string0 = columnDetail0.getOmrsGuid();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      Double double0 = new Double(0.0);
      columnDetail0.setPosition(double0);
      Double double1 = columnDetail0.getPosition();
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      columnDetail0.setName("");
      String string0 = columnDetail0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ColumnDetail columnDetail0 = new ColumnDetail();
      String string0 = columnDetail0.getOmrsGuid();
      assertNull(string0);
  }
}
