/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 15 00:45:08 GMT 2021
 */

package com.ibm.watson.data.client.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.ibm.watson.data.client.model.ExportedDataProtectionRule;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExportedDataProtectionRule_ESTest extends ExportedDataProtectionRule_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ExportedDataProtectionRule exportedDataProtectionRule0 = new ExportedDataProtectionRule();
      ExportedDataProtectionRule exportedDataProtectionRule1 = exportedDataProtectionRule0.guid("57n!&8aGz2}3V");
      String string0 = exportedDataProtectionRule1.getGuid();
      assertEquals("57n!&8aGz2}3V", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ExportedDataProtectionRule exportedDataProtectionRule0 = new ExportedDataProtectionRule();
      exportedDataProtectionRule0.setGuid("");
      String string0 = exportedDataProtectionRule0.getGuid();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ExportedDataProtectionRule exportedDataProtectionRule0 = new ExportedDataProtectionRule();
      exportedDataProtectionRule0.trigger((List<Object>) null);
      ExportedDataProtectionRule exportedDataProtectionRule1 = new ExportedDataProtectionRule();
      boolean boolean0 = exportedDataProtectionRule0.equals(exportedDataProtectionRule1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ExportedDataProtectionRule exportedDataProtectionRule0 = new ExportedDataProtectionRule();
      boolean boolean0 = exportedDataProtectionRule0.equals("4NWgw'X#6HNC5oS_7-");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ExportedDataProtectionRule exportedDataProtectionRule0 = new ExportedDataProtectionRule();
      boolean boolean0 = exportedDataProtectionRule0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ExportedDataProtectionRule exportedDataProtectionRule0 = new ExportedDataProtectionRule();
      boolean boolean0 = exportedDataProtectionRule0.equals(exportedDataProtectionRule0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ExportedDataProtectionRule exportedDataProtectionRule0 = new ExportedDataProtectionRule();
      String string0 = exportedDataProtectionRule0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ExportedDataProtectionRule exportedDataProtectionRule0 = new ExportedDataProtectionRule();
      ExportedDataProtectionRule exportedDataProtectionRule1 = exportedDataProtectionRule0.guid("57n!&8aGz2}3V");
      ExportedDataProtectionRule exportedDataProtectionRule2 = new ExportedDataProtectionRule();
      boolean boolean0 = exportedDataProtectionRule1.equals(exportedDataProtectionRule2);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ExportedDataProtectionRule exportedDataProtectionRule0 = new ExportedDataProtectionRule();
      exportedDataProtectionRule0.hashCode();
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      ExportedDataProtectionRule exportedDataProtectionRule0 = new ExportedDataProtectionRule();
      String string0 = exportedDataProtectionRule0.getGuid();
      assertNull(string0);
  }
}
