/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 15 00:59:30 GMT 2021
 */

package com.ibm.watson.data.client.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.ibm.watson.data.client.model.GlossaryCreateResponse;
import com.ibm.watson.data.client.model.GlossaryResource;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GlossaryCreateResponse_ESTest extends GlossaryCreateResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GlossaryCreateResponse glossaryCreateResponse0 = new GlossaryCreateResponse();
      LinkedList<GlossaryResource> linkedList0 = new LinkedList<GlossaryResource>();
      GlossaryCreateResponse glossaryCreateResponse1 = glossaryCreateResponse0.resources(linkedList0);
      List<GlossaryResource> list0 = glossaryCreateResponse1.getResources();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GlossaryCreateResponse glossaryCreateResponse0 = new GlossaryCreateResponse();
      GlossaryResource glossaryResource0 = new GlossaryResource();
      glossaryCreateResponse0.addResourcesItem(glossaryResource0);
      List<GlossaryResource> list0 = glossaryCreateResponse0.getResources();
      assertTrue(list0.contains(glossaryResource0));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GlossaryCreateResponse glossaryCreateResponse0 = new GlossaryCreateResponse();
      GlossaryResource glossaryResource0 = new GlossaryResource();
      GlossaryCreateResponse glossaryCreateResponse1 = glossaryCreateResponse0.addResourcesItem(glossaryResource0);
      String string0 = glossaryCreateResponse1.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GlossaryCreateResponse glossaryCreateResponse0 = new GlossaryCreateResponse();
      boolean boolean0 = glossaryCreateResponse0.equals("|abh:_pM)-f/00");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GlossaryCreateResponse glossaryCreateResponse0 = new GlossaryCreateResponse();
      GlossaryCreateResponse glossaryCreateResponse1 = new GlossaryCreateResponse();
      boolean boolean0 = glossaryCreateResponse0.equals(glossaryCreateResponse1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GlossaryCreateResponse glossaryCreateResponse0 = new GlossaryCreateResponse();
      boolean boolean0 = glossaryCreateResponse0.equals(glossaryCreateResponse0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GlossaryCreateResponse glossaryCreateResponse0 = new GlossaryCreateResponse();
      boolean boolean0 = glossaryCreateResponse0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GlossaryCreateResponse glossaryCreateResponse0 = new GlossaryCreateResponse();
      GlossaryResource glossaryResource0 = new GlossaryResource();
      GlossaryCreateResponse glossaryCreateResponse1 = glossaryCreateResponse0.addResourcesItem(glossaryResource0);
      GlossaryCreateResponse glossaryCreateResponse2 = glossaryCreateResponse1.addResourcesItem(glossaryResource0);
      assertSame(glossaryCreateResponse0, glossaryCreateResponse2);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GlossaryCreateResponse glossaryCreateResponse0 = new GlossaryCreateResponse();
      List<GlossaryResource> list0 = glossaryCreateResponse0.getResources();
      glossaryCreateResponse0.setResources(list0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GlossaryCreateResponse glossaryCreateResponse0 = new GlossaryCreateResponse();
      String string0 = glossaryCreateResponse0.toString();
      assertEquals("class GlossaryCreateResponse {\n    resources: null\n}", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GlossaryCreateResponse glossaryCreateResponse0 = new GlossaryCreateResponse();
      glossaryCreateResponse0.hashCode();
  }
}
