/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 14 18:30:23 GMT 2021
 */

package com.ibm.watson.data.client.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.ibm.watson.data.client.model.GlossaryResource;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GlossaryResource_ESTest extends GlossaryResource_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      String string0 = glossaryResource0.toIndentedString("");
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      glossaryResource0.setWorkflowId("oz>3jh");
      String string0 = glossaryResource0.getWorkflowId();
      assertEquals("oz>3jh", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      GlossaryResource glossaryResource1 = glossaryResource0.versionId("d$7^PT&");
      String string0 = glossaryResource1.getVersionId();
      assertEquals("d$7^PT&", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      glossaryResource0.versionId("");
      String string0 = glossaryResource0.getVersionId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      glossaryResource0.setHref("[Ic6{");
      String string0 = glossaryResource0.getHref();
      assertEquals("[Ic6{", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      GlossaryResource glossaryResource1 = glossaryResource0.href("");
      String string0 = glossaryResource1.getHref();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      glossaryResource0.globalId("VyM,%o?");
      String string0 = glossaryResource0.getGlobalId();
      assertEquals("VyM,%o?", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      GlossaryResource glossaryResource1 = glossaryResource0.globalId("");
      String string0 = glossaryResource1.getGlobalId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      GlossaryResource glossaryResource1 = glossaryResource0.entityType("com.ibm.watson.data.client.model.GlossaryResource");
      String string0 = glossaryResource1.getEntityType();
      assertEquals("com.ibm.watson.data.client.model.GlossaryResource", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      GlossaryResource glossaryResource1 = glossaryResource0.entityType("");
      String string0 = glossaryResource1.getEntityType();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      glossaryResource0.setArtifactId("-sE*Nck)6(0F'KH0");
      String string0 = glossaryResource0.getArtifactId();
      assertEquals("-sE*Nck)6(0F'KH0", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      glossaryResource0.artifactId("");
      String string0 = glossaryResource0.getArtifactId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      // Undeclared exception!
      try { 
        glossaryResource0.toString((StringBuilder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.ibm.watson.data.client.model.GlossaryResource", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      StringBuilder stringBuilder0 = new StringBuilder(3667);
      glossaryResource0.toString(stringBuilder0);
      assertEquals("    href: null\n    artifactId: null\n    versionId: null\n    workflowId: null\n    globalId: null\n    entityType: null\n", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      glossaryResource0.setHref("");
      String string0 = glossaryResource0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      GlossaryResource glossaryResource1 = glossaryResource0.entityType("");
      GlossaryResource glossaryResource2 = new GlossaryResource();
      boolean boolean0 = glossaryResource1.equals(glossaryResource2);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      GlossaryResource glossaryResource1 = glossaryResource0.globalId("");
      GlossaryResource glossaryResource2 = new GlossaryResource();
      boolean boolean0 = glossaryResource1.equals(glossaryResource2);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      GlossaryResource glossaryResource1 = new GlossaryResource();
      assertTrue(glossaryResource1.equals((Object)glossaryResource0));
      
      glossaryResource0.workflowId("");
      boolean boolean0 = glossaryResource0.equals(glossaryResource1);
      assertFalse(glossaryResource1.equals((Object)glossaryResource0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      GlossaryResource glossaryResource1 = new GlossaryResource();
      assertTrue(glossaryResource1.equals((Object)glossaryResource0));
      
      glossaryResource1.versionId("");
      boolean boolean0 = glossaryResource0.equals(glossaryResource1);
      assertFalse(glossaryResource1.equals((Object)glossaryResource0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      GlossaryResource glossaryResource1 = new GlossaryResource();
      boolean boolean0 = glossaryResource0.equals(glossaryResource1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      Object object0 = new Object();
      boolean boolean0 = glossaryResource0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      boolean boolean0 = glossaryResource0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      boolean boolean0 = glossaryResource0.equals(glossaryResource0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      String string0 = glossaryResource0.getGlobalId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      glossaryResource0.setGlobalId((String) null);
      assertNull(glossaryResource0.getWorkflowId());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      glossaryResource0.setArtifactId("USE_DEFAULTS");
      GlossaryResource glossaryResource1 = new GlossaryResource();
      boolean boolean0 = glossaryResource0.equals(glossaryResource1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      String string0 = glossaryResource0.getArtifactId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      glossaryResource0.hashCode();
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      String string0 = glossaryResource0.getEntityType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      glossaryResource0.setWorkflowId("");
      String string0 = glossaryResource0.getWorkflowId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      glossaryResource0.setVersionId((String) null);
      assertNull(glossaryResource0.getVersionId());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      String string0 = glossaryResource0.getVersionId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      glossaryResource0.setHref("");
      GlossaryResource glossaryResource1 = new GlossaryResource();
      boolean boolean0 = glossaryResource0.equals(glossaryResource1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      String string0 = glossaryResource0.getWorkflowId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      glossaryResource0.setEntityType("class GlossaryResource {\n    href: null\n    artifactId: java.lang.String@0000000002\n    versionId: null\n    workflowId: null\n    globalId: null\n    entityType: null\n}");
      assertNull(glossaryResource0.getWorkflowId());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      GlossaryResource glossaryResource0 = new GlossaryResource();
      String string0 = glossaryResource0.getHref();
      assertNull(string0);
  }
}
