/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 15 01:38:51 GMT 2021
 */

package com.ibm.watson.data.client.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.ibm.watson.data.client.model.JobRunPostBody;
import com.ibm.watson.data.client.model.JobRunPostBodyJobRun;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JobRunPostBody_ESTest extends JobRunPostBody_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JobRunPostBody jobRunPostBody0 = new JobRunPostBody();
      JobRunPostBodyJobRun jobRunPostBodyJobRun0 = new JobRunPostBodyJobRun();
      JobRunPostBody jobRunPostBody1 = jobRunPostBody0.jobRun(jobRunPostBodyJobRun0);
      JobRunPostBodyJobRun jobRunPostBodyJobRun1 = jobRunPostBody1.getJobRun();
      assertSame(jobRunPostBodyJobRun1, jobRunPostBodyJobRun0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JobRunPostBody jobRunPostBody0 = new JobRunPostBody();
      JobRunPostBody jobRunPostBody1 = new JobRunPostBody();
      boolean boolean0 = jobRunPostBody0.equals(jobRunPostBody1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      JobRunPostBody jobRunPostBody0 = new JobRunPostBody();
      JobRunPostBodyJobRun jobRunPostBodyJobRun0 = new JobRunPostBodyJobRun();
      boolean boolean0 = jobRunPostBody0.equals(jobRunPostBodyJobRun0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      JobRunPostBody jobRunPostBody0 = new JobRunPostBody();
      boolean boolean0 = jobRunPostBody0.equals(jobRunPostBody0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      JobRunPostBody jobRunPostBody0 = new JobRunPostBody();
      boolean boolean0 = jobRunPostBody0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      JobRunPostBody jobRunPostBody0 = new JobRunPostBody();
      String string0 = jobRunPostBody0.toString();
      assertEquals("class JobRunPostBody {\n    jobRun: null\n}", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      JobRunPostBody jobRunPostBody0 = new JobRunPostBody();
      jobRunPostBody0.hashCode();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      JobRunPostBody jobRunPostBody0 = new JobRunPostBody();
      JobRunPostBodyJobRun jobRunPostBodyJobRun0 = new JobRunPostBodyJobRun();
      jobRunPostBody0.setJobRun(jobRunPostBodyJobRun0);
      String string0 = jobRunPostBody0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      JobRunPostBody jobRunPostBody0 = new JobRunPostBody();
      JobRunPostBodyJobRun jobRunPostBodyJobRun0 = jobRunPostBody0.getJobRun();
      assertNull(jobRunPostBodyJobRun0);
  }
}
