/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 14 13:56:38 GMT 2021
 */

package com.ibm.watson.data.client.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.ibm.watson.data.client.model.CommitInfo;
import com.ibm.watson.data.client.model.MetadataAsset;
import com.ibm.watson.data.client.model.MetadataRov;
import com.ibm.watson.data.client.model.MetadataUsage;
import com.ibm.watson.data.client.model.SourceAsset;
import com.ibm.watson.data.client.model.SourceSystem;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;
import org.testng.xml.XmlDefine;
import org.testng.xml.XmlSuite;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MetadataAsset_ESTest extends MetadataAsset_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Double double0 = new Double(0.0);
      metadataAsset0.version(double0);
      Double double1 = metadataAsset0.getVersion();
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Double double0 = new Double(0.5);
      metadataAsset0.version(double0);
      Double double1 = metadataAsset0.getVersion();
      assertEquals(0.5, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Double double0 = new Double(1093.7068543);
      MetadataAsset metadataAsset1 = metadataAsset0.version(double0);
      Double double1 = metadataAsset1.getVersion();
      assertEquals(1093.7068543, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Double double0 = new Double((-852.13));
      metadataAsset0.version(double0);
      Double double1 = metadataAsset0.getVersion();
      assertEquals((-852.13), (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataUsage metadataUsage0 = new MetadataUsage();
      metadataAsset0.setUsage(metadataUsage0);
      MetadataUsage metadataUsage1 = metadataAsset0.getUsage();
      assertNull(metadataUsage1.getLastAccessorId());
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Long long0 = new Long(0L);
      MetadataAsset metadataAsset1 = metadataAsset0.totalRatings(long0);
      Long long1 = metadataAsset1.getTotalRatings();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Long long0 = new Long(3376L);
      metadataAsset0.totalRatings(long0);
      Long long1 = metadataAsset0.getTotalRatings();
      assertEquals(3376L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Long long0 = new Long((-1809L));
      metadataAsset0.totalRatings(long0);
      Long long1 = metadataAsset0.getTotalRatings();
      assertEquals((-1809L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Long long0 = new Long(995000L);
      metadataAsset0.size(long0);
      Long long1 = metadataAsset0.getSize();
      assertEquals(995000L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Long long0 = new Long(0L);
      metadataAsset0.size(long0);
      Long long1 = metadataAsset0.getSize();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Long long0 = Long.valueOf((-3977L));
      metadataAsset0.size(long0);
      Long long1 = metadataAsset0.getSize();
      assertEquals((-3977L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.sandboxId("");
      String string0 = metadataAsset0.getSandboxId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Long long0 = new Long(0L);
      metadataAsset0.revisionId(long0);
      Long long1 = metadataAsset0.getRevisionId();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Long long0 = new Long(45L);
      MetadataAsset metadataAsset1 = metadataAsset0.revisionId(long0);
      Long long1 = metadataAsset1.getRevisionId();
      assertEquals(45L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = metadataAsset0.resourceKey("%|P<A;");
      String string0 = metadataAsset1.getResourceKey();
      assertEquals("%|P<A;", string0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.resourceKey("");
      String string0 = metadataAsset0.getResourceKey();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Double double0 = new Double((-1193.56923093826));
      MetadataAsset metadataAsset1 = metadataAsset0.rating(double0);
      Double double1 = metadataAsset1.getRating();
      assertEquals((-1193.56923093826), (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Double double0 = new Double(0.0);
      metadataAsset0.rating(double0);
      Double double1 = metadataAsset0.getRating();
      assertEquals(0.0, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Double double0 = new Double(3565.41615892);
      MetadataAsset metadataAsset1 = metadataAsset0.rating(double0);
      Double double1 = metadataAsset1.getRating();
      assertEquals(3565.41615892, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.projectId("A9~31ex<3p&(O/:8>-F");
      String string0 = metadataAsset0.getProjectId();
      assertEquals("A9~31ex<3p&(O/:8>-F", string0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.setProjectId("");
      String string0 = metadataAsset0.getProjectId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = metadataAsset0.ownerId("82y,dM3");
      String string0 = metadataAsset1.getOwnerId();
      assertEquals("82y,dM3", string0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.setDeleteReason("    ownerId: ");
      String string0 = metadataAsset0.getDeleteReason();
      assertEquals("    ownerId: ", string0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.setDeleteProcessingState("EB");
      String string0 = metadataAsset0.getDeleteProcessingState();
      assertEquals("EB", string0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.setDeleteProcessingState("");
      String string0 = metadataAsset0.getDeleteProcessingState();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MockDate mockDate0 = new MockDate((-4289L));
      MetadataAsset metadataAsset1 = metadataAsset0.createdAt(mockDate0);
      Date date0 = metadataAsset1.getCreatedAt();
      assertSame(mockDate0, date0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Long long0 = new Long(0L);
      metadataAsset0.created(long0);
      Long long1 = metadataAsset0.getCreated();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Long long0 = new Long(2878L);
      MetadataAsset metadataAsset1 = metadataAsset0.created(long0);
      Long long1 = metadataAsset1.getCreated();
      assertEquals(2878L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Long long0 = new Long((-1612L));
      metadataAsset0.created(long0);
      Long long1 = metadataAsset0.getCreated();
      assertEquals((-1612L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Vector<SourceSystem> vector0 = new Vector<SourceSystem>();
      metadataAsset0.childSourceSystems(vector0);
      List<SourceSystem> list0 = metadataAsset0.getChildSourceSystems();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.catalogId("rk{");
      String string0 = metadataAsset0.getCatalogId();
      assertEquals("rk{", string0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.catalogId("");
      String string0 = metadataAsset0.getCatalogId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = metadataAsset0.assetState("STARTED");
      String string0 = metadataAsset1.getAssetState();
      assertEquals("STARTED", string0);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.setAssetState("");
      String string0 = metadataAsset0.getAssetState();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.assetId("YDI\"n");
      String string0 = metadataAsset0.getAssetId();
      assertEquals("YDI\"n", string0);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.setAssetId("");
      String string0 = metadataAsset0.getAssetId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      XmlSuite xmlSuite0 = new XmlSuite();
      List<String> list0 = xmlSuite0.getLocalListeners();
      metadataAsset0.assetAttributes(list0);
      List<String> list1 = metadataAsset0.getAssetAttributes();
      assertTrue(list1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Vector<String> vector0 = new Vector<String>();
      vector0.add("FgaDO");
      MetadataAsset metadataAsset1 = metadataAsset0.assetAttributes(vector0);
      List<String> list0 = metadataAsset1.getAssetAttributes();
      assertTrue(list0.contains("FgaDO"));
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      // Undeclared exception!
      try { 
        metadataAsset0.toString((StringBuilder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.ibm.watson.data.client.model.Metadata", e);
      }
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      StringBuilder stringBuilder0 = new StringBuilder("reactor.core.publisher.DelegateProcessor");
      metadataAsset0.toString(stringBuilder0);
      assertEquals("reactor.core.publisher.DelegateProcessor    tags: null\n    assetType: null\n    assetCategory: null\n    name: null\n    description: null\n    originCountry: null\n    resourceKey: null\n    rov: null\n    projectId: null\n    sandboxId: null\n    usage: null\n    deleteProcessingState: null\n    deleteReason: null\n    rating: null\n    totalRatings: null\n    catalogId: null\n    created: null\n    createdAt: null\n    ownerId: null\n    size: null\n    version: null\n    assetState: null\n    assetAttributes: null\n    assetId: null\n    sourceAsset: null\n    sourceSystem: null\n    childSourceSystems: null\n    revisionId: null\n    commitInfo: null\n", stringBuilder0.toString());
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      boolean boolean0 = metadataAsset0.equals(metadataAsset1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      SourceSystem sourceSystem0 = new SourceSystem();
      metadataAsset1.setSourceSystem(sourceSystem0);
      boolean boolean0 = metadataAsset1.equals(metadataAsset0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      SourceAsset sourceAsset0 = new SourceAsset();
      metadataAsset0.sourceAsset(sourceAsset0);
      boolean boolean0 = metadataAsset0.equals(metadataAsset1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      MetadataAsset metadataAsset2 = metadataAsset1.assetId("QCHdiymh]Nl#kjokl");
      boolean boolean0 = metadataAsset0.equals(metadataAsset2);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      XmlDefine xmlDefine0 = new XmlDefine();
      List<String> list0 = xmlDefine0.getIncludes();
      metadataAsset0.assetAttributes(list0);
      boolean boolean0 = metadataAsset0.equals(metadataAsset1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      metadataAsset0.assetState("QCHdiymh]Nl#kjokl");
      boolean boolean0 = metadataAsset0.equals(metadataAsset1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      Double double0 = new Double(781.360342);
      metadataAsset0.version(double0);
      boolean boolean0 = metadataAsset0.equals(metadataAsset1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      Long long0 = new Long(0L);
      metadataAsset0.setSize(long0);
      boolean boolean0 = metadataAsset0.equals(metadataAsset1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      metadataAsset1.ownerId("QCHdiymh]Nl#kjokl");
      boolean boolean0 = metadataAsset1.equals(metadataAsset0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MockDate mockDate0 = new MockDate(1658, 1658, 1658, 1658, 1658);
      metadataAsset0.createdAt(mockDate0);
      MetadataAsset metadataAsset1 = new MetadataAsset();
      boolean boolean0 = metadataAsset0.equals(metadataAsset1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      Long long0 = new Long(0L);
      metadataAsset0.setCreated(long0);
      boolean boolean0 = metadataAsset0.equals(metadataAsset1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      metadataAsset0.setCatalogId("Jj76M-o>:*");
      boolean boolean0 = metadataAsset0.equals(metadataAsset1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      Long long0 = new Long(0L);
      metadataAsset1.setTotalRatings(long0);
      boolean boolean0 = metadataAsset0.equals(metadataAsset1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      Double double0 = new Double(0.0);
      metadataAsset1.rating(double0);
      boolean boolean0 = metadataAsset1.equals(metadataAsset0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      metadataAsset1.setDeleteReason("w=>ce>vAM.%sYK*G");
      boolean boolean0 = metadataAsset0.equals(metadataAsset1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      MetadataAsset metadataAsset2 = metadataAsset1.sandboxId("QCHdiymh]Nl#kjokl");
      boolean boolean0 = metadataAsset0.equals(metadataAsset2);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      MetadataAsset metadataAsset2 = metadataAsset1.projectId("E(JYV/Uq!");
      boolean boolean0 = metadataAsset0.equals(metadataAsset2);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      MetadataRov metadataRov0 = new MetadataRov();
      MetadataAsset metadataAsset2 = metadataAsset1.rov(metadataRov0);
      boolean boolean0 = metadataAsset0.equals(metadataAsset2);
      assertFalse(metadataAsset1.equals((Object)metadataAsset0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      assertTrue(metadataAsset1.equals((Object)metadataAsset0));
      
      metadataAsset0.resourceKey("QCHdiymh]Nl#kjokl");
      boolean boolean0 = metadataAsset0.equals(metadataAsset1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = new MetadataAsset();
      metadataAsset0.setName("QCHdiymh]Nl#kjokl");
      boolean boolean0 = metadataAsset0.equals(metadataAsset1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      boolean boolean0 = metadataAsset0.equals("G");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      boolean boolean0 = metadataAsset0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      boolean boolean0 = metadataAsset0.equals(metadataAsset0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      LinkedList<SourceSystem> linkedList0 = new LinkedList<SourceSystem>();
      MetadataAsset metadataAsset1 = metadataAsset0.childSourceSystems(linkedList0);
      MetadataAsset metadataAsset2 = new MetadataAsset();
      boolean boolean0 = metadataAsset1.equals(metadataAsset2);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      SourceSystem sourceSystem0 = new SourceSystem();
      metadataAsset0.addChildSourceSystemsItem(sourceSystem0);
      List<SourceSystem> list0 = metadataAsset0.getChildSourceSystems();
      assertTrue(list0.contains(sourceSystem0));
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataAsset metadataAsset1 = metadataAsset0.ownerId("");
      String string0 = metadataAsset1.getOwnerId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      SourceSystem sourceSystem0 = metadataAsset0.getSourceSystem();
      assertNull(sourceSystem0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      CommitInfo commitInfo0 = new CommitInfo();
      metadataAsset0.setCommitInfo(commitInfo0);
      assertNull(metadataAsset0.getDeleteReason());
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      String string0 = metadataAsset0.getOwnerId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      String string0 = metadataAsset0.getAssetId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.setResourceKey("B5g&P`k");
      assertNull(metadataAsset0.getAssetState());
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.sandboxId("t");
      String string0 = metadataAsset0.getSandboxId();
      assertEquals("t", string0);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      String string0 = metadataAsset0.toString();
      assertEquals("class MetadataAsset {\n    tags: null\n    assetType: null\n    assetCategory: null\n    name: null\n    description: null\n    originCountry: null\n    resourceKey: null\n    rov: null\n    projectId: null\n    sandboxId: null\n    usage: null\n    deleteProcessingState: null\n    deleteReason: null\n    rating: null\n    totalRatings: null\n    catalogId: null\n    created: null\n    createdAt: null\n    ownerId: null\n    size: null\n    version: null\n    assetState: null\n    assetAttributes: null\n    assetId: null\n    sourceAsset: null\n    sourceSystem: null\n    childSourceSystems: null\n    revisionId: null\n    commitInfo: null\n}", string0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.setSandboxId("Can't invoke handlerAdded() as the EventExecutor {} rejected it, removing handler {}.");
      assertNull(metadataAsset0.getCatalogId());
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Long long0 = metadataAsset0.getRevisionId();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      String string0 = metadataAsset0.getSandboxId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.setCreatedAt((Date) null);
      assertNull(metadataAsset0.getVersion());
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      CommitInfo commitInfo0 = metadataAsset0.getCommitInfo();
      assertNull(commitInfo0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      String string0 = metadataAsset0.getDeleteProcessingState();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      XmlSuite xmlSuite0 = new XmlSuite();
      List<String> list0 = xmlSuite0.getIncludedGroups();
      metadataAsset0.setAssetAttributes(list0);
      assertNull(metadataAsset0.getAssetState());
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataUsage metadataUsage0 = metadataAsset0.getUsage();
      assertNull(metadataUsage0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Double double0 = metadataAsset0.getVersion();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.setOwnerId("t");
      assertNull(metadataAsset0.getAssetState());
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      String string0 = metadataAsset0.getProjectId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Long long0 = metadataAsset0.getCreated();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataRov metadataRov0 = new MetadataRov();
      metadataAsset0.setRov(metadataRov0);
      assertNull(metadataAsset0.getOriginCountry());
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      CommitInfo commitInfo0 = new CommitInfo();
      MetadataAsset metadataAsset1 = metadataAsset0.commitInfo(commitInfo0);
      CommitInfo commitInfo1 = metadataAsset1.getCommitInfo();
      assertSame(commitInfo1, commitInfo0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Long long0 = new Long((-1L));
      metadataAsset0.setRevisionId(long0);
      Long long1 = metadataAsset0.getRevisionId();
      assertEquals((-1L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Date date0 = metadataAsset0.getCreatedAt();
      assertNull(date0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      SourceSystem sourceSystem0 = new SourceSystem();
      metadataAsset0.sourceSystem(sourceSystem0);
      SourceSystem sourceSystem1 = metadataAsset0.getSourceSystem();
      assertSame(sourceSystem1, sourceSystem0);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      String string0 = metadataAsset0.getAssetState();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Double double0 = new Double(1382.323727);
      metadataAsset0.setRating(double0);
      Double double1 = metadataAsset0.getRating();
      assertEquals(1382.323727, (double)double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Double double0 = new Double(0.0);
      metadataAsset0.setVersion(double0);
      assertNull(metadataAsset0.getTotalRatings());
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      SourceAsset sourceAsset0 = new SourceAsset();
      metadataAsset0.setSourceAsset(sourceAsset0);
      assertNull(metadataAsset0.getAssetState());
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataRov metadataRov0 = metadataAsset0.getRov();
      assertNull(metadataRov0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      String string0 = metadataAsset0.getResourceKey();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      SourceAsset sourceAsset0 = new SourceAsset();
      metadataAsset0.sourceAsset(sourceAsset0);
      SourceAsset sourceAsset1 = metadataAsset0.getSourceAsset();
      assertNull(sourceAsset1.getAction());
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      String string0 = metadataAsset0.getCatalogId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Long long0 = metadataAsset0.getSize();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.hashCode();
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.setChildSourceSystems((List<SourceSystem>) null);
      assertNull(metadataAsset0.getVersion());
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      LinkedList<SourceSystem> linkedList0 = new LinkedList<SourceSystem>();
      MetadataAsset metadataAsset1 = metadataAsset0.childSourceSystems(linkedList0);
      SourceSystem sourceSystem0 = new SourceSystem();
      metadataAsset1.addChildSourceSystemsItem(sourceSystem0);
      assertTrue(linkedList0.contains(sourceSystem0));
      assertEquals(1, linkedList0.size());
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      String string0 = metadataAsset0.getDeleteReason();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataRov metadataRov0 = new MetadataRov();
      metadataAsset0.rov(metadataRov0);
      MetadataRov metadataRov1 = metadataAsset0.getRov();
      assertSame(metadataRov1, metadataRov0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataUsage metadataUsage0 = new MetadataUsage();
      MetadataAsset metadataAsset1 = metadataAsset0.usage(metadataUsage0);
      assertNull(metadataAsset1.getName());
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Long long0 = metadataAsset0.getTotalRatings();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      SourceAsset sourceAsset0 = metadataAsset0.getSourceAsset();
      assertNull(sourceAsset0);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      List<String> list0 = metadataAsset0.getAssetAttributes();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      metadataAsset0.setDeleteProcessingState("_FceIx'");
      MetadataAsset metadataAsset1 = new MetadataAsset();
      boolean boolean0 = metadataAsset0.equals(metadataAsset1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      List<SourceSystem> list0 = metadataAsset0.getChildSourceSystems();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      Double double0 = metadataAsset0.getRating();
      assertNull(double0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      MetadataAsset metadataAsset0 = new MetadataAsset();
      MetadataUsage metadataUsage0 = new MetadataUsage();
      metadataAsset0.setUsage(metadataUsage0);
      MetadataAsset metadataAsset1 = new MetadataAsset();
      boolean boolean0 = metadataAsset0.equals(metadataAsset1);
      assertFalse(boolean0);
  }
}
