/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Apr 14 13:56:38 GMT 2021
 */

package com.ibm.watson.data.client.model;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class MetadataAsset_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.ibm.watson.data.client.model.MetadataAsset"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "BR"); 
    java.lang.System.setProperty("user.dir", "/home/cassioegc/tcc/watson-data-api-clients/java"); 
    java.lang.System.setProperty("user.home", "/home/cassioegc"); 
    java.lang.System.setProperty("user.language", "pt"); 
    java.lang.System.setProperty("user.name", "cassioegc"); 
    java.lang.System.setProperty("user.timezone", "America/Recife"); 
    java.lang.System.setProperty("sun.arch.data.model", "64"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(MetadataAsset_ESTest_scaffolding.class.getClassLoader() ,
      "org.testng.collections.Lists",
      "com.beust.jcommander.ParameterException",
      "com.ibm.watson.data.client.model.MetadataUsage",
      "com.ibm.watson.data.client.model.MetadataRov",
      "com.ibm.watson.data.client.model.BaseRov",
      "org.testng.log4testng.Logger",
      "com.ibm.watson.data.client.model.Metadata",
      "org.testng.TestNGException",
      "com.ibm.watson.data.client.model.enums.AssetCategory",
      "org.testng.xml.XmlDefine",
      "org.testng.TestNG",
      "org.testng.IAnnotationTransformer",
      "org.testng.xml.XmlTest",
      "org.testng.ISuite",
      "org.testng.internal.IConfiguration",
      "org.testng.xml.XmlMethodSelectors",
      "org.testng.ITestObjectFactory",
      "org.testng.xml.XmlSuite",
      "org.testng.xml.XmlSuite$FailurePolicy",
      "org.testng.xml.IPostProcessor",
      "org.testng.ITestNGListener",
      "com.ibm.watson.data.client.model.SourceSystem",
      "org.testng.xml.XmlGroups",
      "org.testng.IAttributes",
      "com.ibm.watson.data.client.model.SourceAsset",
      "com.ibm.watson.data.client.model.MetadataAsset",
      "com.ibm.watson.data.client.model.CommitInfo",
      "org.testng.xml.XmlSuite$ParallelMode",
      "org.testng.IDynamicGraph",
      "org.testng.thread.IThreadWorkerFactory",
      "com.ibm.watson.data.client.model.MetadataHeader",
      "org.testng.internal.annotations.IAnnotationFinder",
      "org.testng.collections.Maps"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(MetadataAsset_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.ibm.watson.data.client.model.Metadata",
      "com.ibm.watson.data.client.model.MetadataHeader",
      "com.ibm.watson.data.client.model.MetadataAsset",
      "com.fasterxml.jackson.annotation.JsonProperty$Access",
      "com.fasterxml.jackson.annotation.JsonInclude$Include",
      "com.fasterxml.jackson.annotation.JsonCreator$Mode",
      "org.springframework.web.bind.annotation.RequestMethod",
      "org.springframework.context.annotation.ScopedProxyMode",
      "org.testng.xml.XmlSuite$ParallelMode",
      "org.testng.xml.XmlSuite$FailurePolicy",
      "org.testng.xml.XmlSuite",
      "org.testng.collections.Lists",
      "org.testng.collections.Maps",
      "org.testng.util.Strings",
      "org.testng.internal.RuntimeBehavior",
      "org.testng.log4testng.Logger",
      "org.testng.TestNG",
      "com.ibm.watson.data.client.model.MetadataUsage",
      "com.ibm.watson.data.client.model.SourceSystem",
      "com.ibm.watson.data.client.model.BaseRov",
      "com.ibm.watson.data.client.model.MetadataRov",
      "io.netty.channel.ChannelHandlerAdapter",
      "io.netty.channel.ChannelInboundHandlerAdapter",
      "io.netty.channel.ChannelDuplexHandler",
      "io.netty.handler.logging.LoggingHandler",
      "io.netty.util.internal.ObjectUtil",
      "io.netty.util.internal.logging.InternalLoggerFactory",
      "io.netty.util.internal.logging.Slf4JLoggerFactory",
      "io.netty.util.internal.logging.AbstractInternalLogger",
      "io.netty.util.internal.logging.LocationAwareSlf4JLogger",
      "io.netty.util.DefaultAttributeMap",
      "io.netty.channel.AbstractChannel",
      "io.netty.util.internal.ThrowableUtil",
      "io.netty.channel.ChannelMetadata",
      "io.netty.channel.epoll.AbstractEpollChannel",
      "io.netty.util.internal.SystemPropertyUtil",
      "io.netty.util.internal.SystemPropertyUtil$1",
      "io.netty.util.internal.StringUtil",
      "io.netty.channel.epoll.AbstractEpollStreamChannel",
      "io.netty.channel.epoll.EpollDomainSocketChannel",
      "io.netty.channel.unix.ErrorsStaticallyReferencedJniMethods",
      "io.netty.channel.unix.Errors",
      "io.netty.channel.unix.FileDescriptor",
      "com.ibm.watson.data.client.model.SourceAsset",
      "org.testng.internal.Configuration",
      "org.testng.internal.thread.DefaultThreadPoolExecutorFactory",
      "org.testng.internal.GuiceBackedInjectorFactory",
      "org.testng.internal.annotations.JDK15AnnotationFinder",
      "org.testng.internal.annotations.IgnoreListener",
      "org.testng.internal.annotations.DefaultAnnotationTransformer",
      "org.testng.internal.annotations.JDK15TagFactory",
      "org.testng.SuiteRunner",
      "org.testng.DataProviderHolder",
      "org.testng.collections.Sets",
      "org.testng.TestListenerAdapter",
      "org.testng.SuiteRunState",
      "org.testng.internal.Attributes",
      "org.testng.internal.Utils",
      "com.ibm.watson.data.client.model.CommitInfo",
      "org.testng.xml.XmlGroups",
      "org.testng.xml.XmlDefine",
      "io.netty.util.internal.PlatformDependent0$1",
      "io.netty.util.internal.ReflectionUtil",
      "io.netty.util.internal.PlatformDependent0$2",
      "io.netty.util.internal.PlatformDependent0$3",
      "io.netty.util.internal.PlatformDependent0$4",
      "io.netty.util.internal.PlatformDependent0$5",
      "io.netty.util.internal.PlatformDependent0$10",
      "io.netty.util.internal.PlatformDependent0",
      "io.netty.util.internal.PlatformDependent$1",
      "io.netty.util.internal.PlatformDependent$2",
      "io.netty.util.internal.CleanerJava6$1",
      "io.netty.util.internal.CleanerJava6",
      "io.netty.util.internal.PlatformDependent$4",
      "io.netty.util.internal.PlatformDependent",
      "io.netty.util.internal.PlatformDependent0$8",
      "io.netty.util.internal.EmptyArrays",
      "io.netty.util.internal.MacAddressUtil",
      "io.netty.util.NetUtilInitializations",
      "io.netty.util.NetUtil",
      "io.netty.channel.DefaultChannelId",
      "org.springframework.http.server.reactive.ServerHttpResponseDecorator",
      "org.springframework.util.Assert",
      "org.springframework.http.server.reactive.HttpHeadResponseDecorator",
      "org.testng.xml.XmlRun",
      "org.testng.SuiteRunner$ProxyTestRunnerFactory",
      "org.testng.xml.XmlTest",
      "org.testng.TestRunner",
      "org.testng.GuiceHelper",
      "org.testng.TestRunner$ConfigurationListener",
      "org.testng.internal.XmlMethodSelector",
      "org.testng.collections.MultiMap",
      "org.testng.collections.ListMultiMap",
      "org.testng.internal.ResultMap",
      "org.testng.internal.RunInfo",
      "org.testng.PreserveOrderMethodInterceptor",
      "org.testng.internal.Invoker",
      "org.testng.internal.BaseInvoker",
      "org.testng.internal.ConfigInvoker",
      "org.testng.internal.TestInvoker",
      "org.testng.internal.GroupsHelper",
      "org.testng.internal.MethodSelectorDescriptor",
      "org.testng.internal.ClassInfoMap",
      "org.testng.internal.BaseClassFinder",
      "org.testng.internal.TestNGClassFinder",
      "org.testng.internal.ObjectFactoryImpl",
      "org.testng.internal.TestNGMethodFinder",
      "org.testng.internal.MethodGroupsHelper",
      "org.testng.internal.MethodHelper",
      "org.testng.internal.Graph",
      "org.testng.ClassMethodMap",
      "org.testng.internal.ConfigurationGroupMethods",
      "org.testng.internal.TestListenerHelper",
      "org.testng.internal.DefaultListenerFactory",
      "io.netty.util.concurrent.AbstractEventExecutorGroup",
      "io.netty.util.concurrent.MultithreadEventExecutorGroup",
      "io.netty.util.concurrent.DefaultEventExecutorGroup",
      "io.netty.util.concurrent.AbstractEventExecutor",
      "io.netty.util.concurrent.AbstractScheduledEventExecutor$1",
      "io.netty.util.concurrent.AbstractScheduledEventExecutor$2",
      "io.netty.util.concurrent.AbstractScheduledEventExecutor",
      "io.netty.util.concurrent.SingleThreadEventExecutor$1",
      "io.netty.util.concurrent.SingleThreadEventExecutor",
      "io.netty.util.concurrent.RejectedExecutionHandlers$1",
      "io.netty.util.concurrent.RejectedExecutionHandlers",
      "io.netty.util.concurrent.DefaultEventExecutorChooserFactory",
      "io.netty.util.concurrent.AbstractFuture",
      "io.netty.util.concurrent.DefaultPromise$CauseHolder",
      "io.netty.util.concurrent.DefaultPromise$StacklessCancellationException",
      "io.netty.util.concurrent.DefaultPromise",
      "io.netty.util.concurrent.PromiseTask$SentinelRunnable",
      "io.netty.util.concurrent.PromiseTask",
      "io.netty.util.concurrent.ScheduledFutureTask",
      "io.netty.util.concurrent.GlobalEventExecutor$1",
      "io.netty.util.concurrent.GlobalEventExecutor$TaskRunner",
      "io.netty.util.concurrent.CompleteFuture",
      "io.netty.util.concurrent.FailedFuture",
      "io.netty.util.internal.DefaultPriorityQueue",
      "io.netty.util.concurrent.DefaultThreadFactory",
      "io.netty.util.internal.UnpaddedInternalThreadLocalMap",
      "io.netty.util.internal.InternalThreadLocalMap",
      "io.netty.util.concurrent.FastThreadLocal",
      "io.netty.util.internal.ThreadExecutorMap",
      "io.netty.util.internal.ThreadExecutorMap$3",
      "io.netty.util.concurrent.GlobalEventExecutor",
      "io.netty.util.concurrent.ThreadPerTaskExecutor",
      "io.netty.util.concurrent.DefaultEventExecutor",
      "io.netty.util.internal.ThreadExecutorMap$1",
      "io.netty.util.concurrent.SingleThreadEventExecutor$4",
      "io.netty.util.internal.ThreadExecutorMap$2",
      "io.netty.util.concurrent.FastThreadLocalRunnable",
      "io.netty.util.concurrent.FastThreadLocalThread",
      "org.testng.internal.Systematiser",
      "org.testng.internal.Systematiser$Order",
      "org.testng.internal.Systematiser$4",
      "org.testng.internal.Systematiser$3",
      "org.testng.internal.MethodInstance$1",
      "org.testng.internal.MethodInstance",
      "org.testng.internal.DynamicGraphHelper",
      "org.testng.internal.DynamicGraph",
      "org.testng.internal.DynamicGraph$Edges",
      "org.testng.DependencyMap",
      "org.testng.SuiteRunner$DefaultTestRunnerFactory",
      "org.testng.junit.JUnitTestClass",
      "org.testng.junit.JUnit4TestClass",
      "org.testng.internal.ClassHelper",
      "org.testng.internal.NoOpTestClass",
      "org.testng.xml.XmlClass",
      "org.testng.junit.JUnit3TestClass",
      "org.testng.TestNGException",
      "io.netty.channel.epoll.EpollSocketChannel",
      "org.testng.reporters.RuntimeBehavior",
      "org.testng.reporters.XMLStringBuffer",
      "org.testng.reporters.Buffer",
      "org.testng.reporters.FileStringBuffer",
      "org.testng.collections.CollectionUtils",
      "io.netty.channel.embedded.EmbeddedSocketAddress",
      "io.netty.channel.embedded.EmbeddedChannel",
      "io.netty.channel.embedded.EmbeddedChannelId",
      "io.netty.channel.VoidChannelPromise",
      "io.netty.channel.DefaultChannelPromise",
      "io.netty.channel.AbstractChannel$CloseFuture",
      "io.netty.channel.AbstractChannel$AbstractUnsafe",
      "io.netty.channel.embedded.EmbeddedChannel$EmbeddedUnsafe",
      "io.netty.channel.ChannelOutboundBuffer$1",
      "io.netty.channel.ChannelOutboundBuffer",
      "io.netty.channel.embedded.EmbeddedChannel$EmbeddedUnsafe$1",
      "io.netty.channel.DefaultChannelPipeline$1",
      "io.netty.channel.DefaultChannelPipeline",
      "io.netty.channel.embedded.EmbeddedChannel$EmbeddedChannelPipeline",
      "io.netty.util.ResourceLeakDetector$Level",
      "io.netty.util.ResourceLeakDetector",
      "io.netty.channel.CompleteChannelFuture",
      "io.netty.channel.SucceededChannelFuture",
      "io.netty.channel.VoidChannelPromise$1",
      "io.netty.channel.AbstractChannelHandlerContext",
      "io.netty.channel.DefaultChannelPipeline$TailContext",
      "io.netty.channel.ChannelHandlerMask$1",
      "io.netty.channel.ChannelHandlerMask",
      "io.netty.channel.ChannelHandlerMask$2",
      "io.netty.channel.DefaultChannelPipeline$HeadContext",
      "io.netty.channel.embedded.EmbeddedEventLoop",
      "io.netty.channel.embedded.EmbeddedChannel$1",
      "io.netty.channel.DefaultMessageSizeEstimator$HandleImpl",
      "io.netty.channel.DefaultMessageSizeEstimator",
      "io.netty.channel.DefaultChannelConfig",
      "io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator",
      "io.netty.channel.AdaptiveRecvByteBufAllocator",
      "io.netty.buffer.ByteBufUtil$1",
      "io.netty.util.CharsetUtil",
      "io.netty.buffer.AbstractByteBufAllocator",
      "io.netty.util.NettyRuntime$AvailableProcessorsHolder",
      "io.netty.util.NettyRuntime",
      "io.netty.buffer.ByteBuf",
      "io.netty.buffer.EmptyByteBuf",
      "io.netty.buffer.PooledByteBufAllocator$1",
      "io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache",
      "io.netty.buffer.SizeClasses",
      "io.netty.buffer.PoolArena",
      "io.netty.buffer.PoolArena$DirectArena",
      "io.netty.buffer.PoolThreadCache",
      "io.netty.util.internal.LongAdderCounter",
      "io.netty.buffer.PoolSubpage",
      "io.netty.buffer.PoolChunkList",
      "io.netty.buffer.PooledByteBufAllocatorMetric",
      "io.netty.buffer.PooledByteBufAllocator",
      "io.netty.buffer.ByteBufUtil$2",
      "io.netty.buffer.ByteBufUtil",
      "io.netty.buffer.ByteBufAllocator",
      "io.netty.channel.WriteBufferWaterMark",
      "io.netty.channel.ChannelInitializer",
      "io.netty.channel.embedded.EmbeddedChannel$2",
      "io.netty.channel.DefaultChannelHandlerContext",
      "io.netty.channel.DefaultChannelPipeline$PendingHandlerCallback",
      "io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask",
      "io.netty.channel.embedded.EmbeddedChannel$State",
      "io.netty.util.internal.logging.AbstractInternalLogger$1",
      "reactor.core.Scannable",
      "reactor.core.publisher.Operators$MonoSubscriber",
      "io.netty.util.concurrent.ImmediateEventExecutor$1",
      "io.netty.util.concurrent.ImmediateEventExecutor$2",
      "io.netty.util.concurrent.ImmediateEventExecutor",
      "org.mockserver.scheduler.Scheduler$SchedulerThreadFactory",
      "io.netty.util.concurrent.UnorderedThreadPoolEventExecutor",
      "io.netty.channel.local.LocalChannel",
      "io.netty.channel.epoll.EpollDatagramChannel",
      "org.testng.xml.XmlPackage",
      "org.testng.internal.thread.graph.GraphThreadPoolExecutor",
      "org.testng.internal.thread.TestNGThreadFactory",
      "org.testng.internal.annotations.BaseAnnotation",
      "org.testng.internal.annotations.TestOrConfiguration",
      "org.testng.internal.annotations.ConfigurationAnnotation",
      "org.testng.internal.ConstructorOrMethod",
      "org.testng.internal.BaseTestMethod",
      "org.testng.internal.ConfigurationMethod",
      "org.testng.xml.XmlMethodSelector",
      "org.testng.xml.XmlWeaver",
      "org.testng.xml.DefaultXmlWeaver",
      "io.netty.util.concurrent.DefaultEventExecutorChooserFactory$GenericEventExecutorChooser",
      "io.netty.util.concurrent.MultithreadEventExecutorGroup$1",
      "io.netty.channel.epoll.AbstractEpollServerChannel",
      "io.netty.channel.epoll.EpollServerDomainSocketChannel",
      "org.testng.junit.JUnitTestMethod",
      "org.testng.junit.JUnit3TestMethod",
      "io.netty.channel.SingleThreadEventLoop",
      "io.netty.channel.DefaultEventLoop",
      "org.testng.internal.WrappedTestNGMethod",
      "org.testng.internal.ClonedMethod",
      "org.testng.internal.TestNGMethod",
      "org.testng.xml.XmlMethodSelectors",
      "io.netty.util.concurrent.SucceededFuture",
      "org.hsqldb.jdbc.JDBCDriver"
    );
  }
}
