/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 14 23:55:44 GMT 2021
 */

package com.ibm.watson.data.client.model;

import org.junit.Test;
import static org.junit.Assert.*;
import com.ibm.watson.data.client.model.SearchRelatedAsset;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SearchRelatedAsset_ESTest extends SearchRelatedAsset_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SearchRelatedAsset searchRelatedAsset0 = new SearchRelatedAsset();
      SearchRelatedAsset searchRelatedAsset1 = searchRelatedAsset0.name("kALAYS");
      String string0 = searchRelatedAsset1.getName();
      assertEquals("kALAYS", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SearchRelatedAsset searchRelatedAsset0 = new SearchRelatedAsset();
      searchRelatedAsset0.setName("");
      String string0 = searchRelatedAsset0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SearchRelatedAsset searchRelatedAsset0 = new SearchRelatedAsset();
      searchRelatedAsset0.setArtifactId("");
      String string0 = searchRelatedAsset0.getArtifactId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SearchRelatedAsset searchRelatedAsset0 = new SearchRelatedAsset();
      searchRelatedAsset0.name("kALAYS");
      String string0 = searchRelatedAsset0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SearchRelatedAsset searchRelatedAsset0 = new SearchRelatedAsset();
      SearchRelatedAsset searchRelatedAsset1 = searchRelatedAsset0.name("kALAYS");
      SearchRelatedAsset searchRelatedAsset2 = new SearchRelatedAsset();
      boolean boolean0 = searchRelatedAsset1.equals(searchRelatedAsset2);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SearchRelatedAsset searchRelatedAsset0 = new SearchRelatedAsset();
      SearchRelatedAsset searchRelatedAsset1 = new SearchRelatedAsset();
      boolean boolean0 = searchRelatedAsset0.equals(searchRelatedAsset1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SearchRelatedAsset searchRelatedAsset0 = new SearchRelatedAsset();
      boolean boolean0 = searchRelatedAsset0.equals("kALAYS");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SearchRelatedAsset searchRelatedAsset0 = new SearchRelatedAsset();
      boolean boolean0 = searchRelatedAsset0.equals(searchRelatedAsset0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SearchRelatedAsset searchRelatedAsset0 = new SearchRelatedAsset();
      boolean boolean0 = searchRelatedAsset0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SearchRelatedAsset searchRelatedAsset0 = new SearchRelatedAsset();
      searchRelatedAsset0.hashCode();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SearchRelatedAsset searchRelatedAsset0 = new SearchRelatedAsset();
      searchRelatedAsset0.setArtifactId("J|-(~1qj6]");
      String string0 = searchRelatedAsset0.getArtifactId();
      assertEquals("J|-(~1qj6]", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SearchRelatedAsset searchRelatedAsset0 = new SearchRelatedAsset();
      searchRelatedAsset0.artifactId("");
      SearchRelatedAsset searchRelatedAsset1 = new SearchRelatedAsset();
      boolean boolean0 = searchRelatedAsset0.equals(searchRelatedAsset1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SearchRelatedAsset searchRelatedAsset0 = new SearchRelatedAsset();
      String string0 = searchRelatedAsset0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SearchRelatedAsset searchRelatedAsset0 = new SearchRelatedAsset();
      String string0 = searchRelatedAsset0.getArtifactId();
      assertNull(string0);
  }
}
