/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 13 19:23:00 GMT 2021
 */

package org.apache.xml.security.stax.impl.transformer.canonicalizer;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.xml.security.stax.impl.transformer.canonicalizer.Canonicalizer11_OmitCommentsTransformer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Canonicalizer11_OmitCommentsTransformer_ESTest extends Canonicalizer11_OmitCommentsTransformer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Canonicalizer11_OmitCommentsTransformer canonicalizer11_OmitCommentsTransformer0 = new Canonicalizer11_OmitCommentsTransformer();
  }
}
