/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 13 18:46:41 GMT 2021
 */

package org.apache.xml.security.stax.securityEvent;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import org.apache.xml.security.stax.ext.XMLSecurityConstants;
import org.apache.xml.security.stax.impl.DocumentContextImpl;
import org.apache.xml.security.stax.securityEvent.SignedElementSecurityEvent;
import org.apache.xml.security.stax.securityToken.InboundSecurityToken;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SignedElementSecurityEvent_ESTest extends SignedElementSecurityEvent_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DocumentContextImpl documentContextImpl0 = new DocumentContextImpl();
      List<XMLSecurityConstants.ContentType> list0 = documentContextImpl0.getProtectionOrder();
      SignedElementSecurityEvent signedElementSecurityEvent0 = new SignedElementSecurityEvent((InboundSecurityToken) null, true, list0);
      assertFalse(signedElementSecurityEvent0.isEncrypted());
  }
}
