/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 04 02:02:34 GMT 2021
 */

package com.graphhopper.reader.osm;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.graphhopper.reader.osm.OSMInputFile;
import java.io.File;
import java.io.IOException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class OSMInputFile_ESTest extends OSMInputFile_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OSMInputFile oSMInputFile0 = null;
      try {
        oSMInputFile0 = new OSMInputFile((File) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.graphhopper.reader.osm.OSMInputFile", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      File file0 = MockFile.createTempFile("]nS", "The strings must not be null");
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/tmp/]nS0The strings must not be null");
      FileSystemHandling.shouldThrowIOException(evoSuiteFile0);
      OSMInputFile oSMInputFile0 = null;
      try {
        oSMInputFile0 = new OSMInputFile(file0);
        fail("Expecting exception: IOException");
      
      } catch(Throwable e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MockFile mockFile0 = new MockFile("9g]i ~6KA", "9g]i ~6KA");
      File file0 = MockFile.createTempFile("L)&RD+-BCu yT4", "9g]i ~6KA", (File) mockFile0);
      OSMInputFile oSMInputFile0 = null;
      try {
        oSMInputFile0 = new OSMInputFile(file0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Input file is not of valid type /home/cassioegc/tcc/graphhopper.reader-osm/core/9g]i ~6KA/9g]i ~6KA/L)&RD+-BCu yT409g]i ~6KA
         //
         verifyException("com.graphhopper.reader.osm.OSMInputFile", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("9g]i ~6KA/9g]i ~6KA");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "P<^NH;u");
      MockFile mockFile0 = new MockFile("9g]i ~6KA", "9g]i ~6KA");
      OSMInputFile oSMInputFile0 = null;
      try {
        oSMInputFile0 = new OSMInputFile(mockFile0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Input file is not of valid type /home/cassioegc/tcc/graphhopper.reader-osm/core/9g]i ~6KA/9g]i ~6KA
         //
         verifyException("com.graphhopper.reader.osm.OSMInputFile", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MockFile mockFile0 = new MockFile("9g]i ~6KA", "9g]i ~6KA");
      OSMInputFile oSMInputFile0 = null;
      try {
        oSMInputFile0 = new OSMInputFile(mockFile0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.io.FileNotFoundException
         //
         verifyException("com.graphhopper.reader.osm.OSMInputFile", e);
      }
  }
}
