/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 15 02:49:52 GMT 2021
 */

package com.ibm.watson.data.client.model.enums;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.ibm.watson.data.client.model.enums.DatasourceTypeEnum;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DatasourceTypeEnum_ESTest extends DatasourceTypeEnum_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DatasourceTypeEnum datasourceTypeEnum0 = DatasourceTypeEnum.fromValue("file");
      assertEquals(DatasourceTypeEnum.FILE, datasourceTypeEnum0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DatasourceTypeEnum[] datasourceTypeEnumArray0 = DatasourceTypeEnum.values();
      assertEquals(3, datasourceTypeEnumArray0.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DatasourceTypeEnum datasourceTypeEnum0 = DatasourceTypeEnum.valueOf("FILE");
      assertEquals(DatasourceTypeEnum.FILE, datasourceTypeEnum0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DatasourceTypeEnum datasourceTypeEnum0 = DatasourceTypeEnum.fromValue("database");
      assertEquals(DatasourceTypeEnum.DATABASE, datasourceTypeEnum0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        DatasourceTypeEnum.fromValue("gjld");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected value 'gjld'
         //
         verifyException("com.ibm.watson.data.client.model.enums.DatasourceTypeEnum", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DatasourceTypeEnum datasourceTypeEnum0 = DatasourceTypeEnum.DATABASE;
      String string0 = datasourceTypeEnum0.toString();
      assertEquals("database", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      DatasourceTypeEnum datasourceTypeEnum0 = DatasourceTypeEnum.DATABASE;
      String string0 = datasourceTypeEnum0.getValue();
      assertEquals("database", string0);
  }
}
