/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 13 22:12:26 GMT 2021
 */

package org.apache.xml.security.signature;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.xml.security.signature.InvalidSignatureValueException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InvalidSignatureValueException_ESTest extends InvalidSignatureValueException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Object[] objectArray0 = new Object[1];
      InvalidSignatureValueException invalidSignatureValueException0 = new InvalidSignatureValueException("N$jRv", objectArray0);
      InvalidSignatureValueException invalidSignatureValueException1 = new InvalidSignatureValueException(invalidSignatureValueException0, "78)kAs", objectArray0);
      assertFalse(invalidSignatureValueException1.equals((Object)invalidSignatureValueException0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      InvalidSignatureValueException invalidSignatureValueException0 = new InvalidSignatureValueException();
      InvalidSignatureValueException invalidSignatureValueException1 = new InvalidSignatureValueException(invalidSignatureValueException0, "");
      assertFalse(invalidSignatureValueException1.equals((Object)invalidSignatureValueException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      InvalidSignatureValueException invalidSignatureValueException0 = new InvalidSignatureValueException("E&.O");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Object[] objectArray0 = new Object[1];
      InvalidSignatureValueException invalidSignatureValueException0 = new InvalidSignatureValueException("N$jRv", objectArray0);
      InvalidSignatureValueException invalidSignatureValueException1 = new InvalidSignatureValueException("TK\"@r %fiJxnMdYkD", invalidSignatureValueException0);
      assertFalse(invalidSignatureValueException1.equals((Object)invalidSignatureValueException0));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Object[] objectArray0 = new Object[1];
      InvalidSignatureValueException invalidSignatureValueException0 = new InvalidSignatureValueException("N$jRv", objectArray0);
      StackTraceElement[] stackTraceElementArray0 = invalidSignatureValueException0.getStackTrace();
      InvalidSignatureValueException invalidSignatureValueException1 = new InvalidSignatureValueException("7o\"l%f{Bi'5B", stackTraceElementArray0, invalidSignatureValueException0);
      assertFalse(invalidSignatureValueException1.equals((Object)invalidSignatureValueException0));
  }
}
