version: '2'
services:
    tccmanager-app:
        image: tccmanager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tccmanager-postgresql:5432/tccmanager
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tccmanager-postgresql:
        extends:
            file: postgresql.yml
            service: tccmanager-postgresql
